[pyprland]
plugins = ["scratchpads", "magnify"]

[scratchpads.terminal]
command = "kitty --class kitty-dropterm"
animation = "fromTop"
size = "75% 50%"
class = "kitty-dropterm"
max_size = "1920px 100%"
margin = 50

[magnify]
factor = 2
duration = 15


